spring.application.name=CTR
#spring.jpa.hibernate.ddl-auto=none
#spring.sql.init.mode=always
#spring.datasource.url=jdbc:mysql://192.168.45.188:3306/ctr?rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
#spring.datasource.username=root
#spring.datasource.password=1234
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql: true
#spring.security.user.name=Kim
#spring.security.user.password=1234
#logging.level.web=DEBUG